services:
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=youremail@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yml:/traefik.yml:ro"
    networks:
      web:


  api:
    image: node:lts-alpine
    container_name: api
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npx prisma generate && npm run dev"
    restart: unless-stopped
    depends_on:
      - traefik
      - mysql
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
      - "traefik.http.services.api.loadbalancer.server.scheme=http"
      - "traefik.http.routers.api.entrypoints=websecure" # Forçando a usar HTTPS
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.rule=Host(`api.questoes.dev.localhost`)"
      - "traefik.http.routers.api.tls.certresolver=myresolver"

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    command: --max_allowed_packet=1073741824
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'local'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uroot", "-ppassword" ]
      retries: 3
      timeout: 5s
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
