services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: questoes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local

# services:
#   mysql:
#     image: mysql:8.0
#     container_name: mysql-container
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: questoes
#       MYSQL_USER: admin
#       MYSQL_PASSWORD: password
#     ports:
#       - "3306:3306"
#     volumes:
#       - ./mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
#     driver: local
