http:
  routers:
    user-service:
      rule: "Host(`user-service.dev.localhost`)"
      service: "user-service"
      tls: {}
      entryPoints:
        - "websecure"

  services:
    user-service:
      loadBalancer:
        servers:
          - url: "http://user-service:3000"

tls:
  certificates:
    - certFile: "/certs/dev.localhost.pem"
      keyFile: "/certs/dev.localhost-key.pem"
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/local-cert.pem"
        keyFile: "/certs/local-key.pem"